version: '3'
services:
  blog:
    build:
      context: ./
      dockerfile: .Dockerfile
    container_name: blog
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./res:/blog/res
      - ./src:/blog/src
